/* dctl_shim.h — minimal host-side emulation of the DaVinci Resolve DCTL
 * environment so a .dctl file can be compiled with gcc/clang as C and
 * exercised with test vectors. It is NOT a full implementation of DCTL; it
 * covers the subset used by the BNC Grade DCTLs. Never ship this file to
 * Resolve — it is only for testing. */
#ifndef DCTL_SHIM_H
#define DCTL_SHIM_H
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define __DEVICE__ static inline
#define __CONSTANT__ static const
#define __RESOLVE_VER_MAJOR__ 19
#define __RESOLVE_VER_MINOR__ 1

typedef struct { float x, y, z; } float3;
static inline float3 make_float3(float x, float y, float z) { float3 v = {x, y, z}; return v; }

/* UI parameter macros: in Resolve these create sliders/checkboxes; here we
 * declare a global initialised to the default value, which the test harness
 * may override via setters generated by DCTL_PARAM_SETTER. */
#define DCTLUI_SLIDER_FLOAT 0
#define DCTLUI_SLIDER_INT 1
#define DCTLUI_CHECK_BOX 2
#define DCTLUI_COMBO_BOX 3
#define DCTLUI_VALUE_BOX 4
#define _DCTL_PARAM_TYPE_0 float
#define _DCTL_PARAM_TYPE_1 int
#define _DCTL_PARAM_TYPE_2 int
#define _DCTL_PARAM_TYPE_4 float
#define _DCTL_CAT(a, b) a##b
#define _DCTL_TYPE(kind) _DCTL_CAT(_DCTL_PARAM_TYPE_, kind)
#define _DCTL_DISPATCH2(kind) _DCTL_DEFINE_##kind
#define _DCTL_DISPATCH(kind) _DCTL_DISPATCH2(kind)
#define DEFINE_UI_PARAMS(name, label, kind, ...) _DCTL_DISPATCH(kind)(name, __VA_ARGS__)
#define _DCTL_DEFINE_0(name, def, ...) static float name = (float)(def);
#define _DCTL_DEFINE_1(name, def, ...) static int name = (int)(def);
#define _DCTL_DEFINE_2(name, def, ...) static int name = (int)(def);
#define _DCTL_DEFINE_4(name, def, ...) static float name = (float)(def);
/* Combo boxes: DEFINE_UI_PARAMS(name, label, DCTLUI_COMBO_BOX, default, {A, B}, {"A","B"})
 *
 * The C preprocessor only treats parentheses as argument-grouping -- braces
 * are ordinary tokens to it -- so a naive fixed-arity _DCTL_DEFINE_3(name,
 * def, enums, labels) macro mis-splits {A, B} and {"A","B"} at their inner
 * commas into extra arguments the moment it is re-invoked with them (this
 * breaks even the 2-item example above). Since the enum list and the label
 * list are always the same length, the fix below counts the comma-split
 * pieces of the combined tail and takes the first half back (which, because
 * splitting-then-rejoining-with-commas is lossless, reconstructs the
 * original {A, B, ...} text -- braces and all -- as the enum body); the
 * label half is left unused. Supports up to 8 combo items. */
#define _DCTL_CAT(a, b) a##b
#define _DCTL_CAT2(a, b) _DCTL_CAT(a, b)
#define _DCTL_ARG_N(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,N,...) N
#define _DCTL_RSEQ_N() 16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
#define _DCTL_NARG_(...) _DCTL_ARG_N(__VA_ARGS__)
#define _DCTL_NARG(...) _DCTL_NARG_(__VA_ARGS__, _DCTL_RSEQ_N())
#define _DCTL_TAKE_HALF_2(a,b) a
#define _DCTL_TAKE_HALF_4(a,b,c,d) a,b
#define _DCTL_TAKE_HALF_6(a,b,c,d,e,f) a,b,c
#define _DCTL_TAKE_HALF_8(a,b,c,d,e,f,g,h) a,b,c,d
#define _DCTL_TAKE_HALF_10(a,b,c,d,e,f,g,h,i,j) a,b,c,d,e
#define _DCTL_TAKE_HALF_12(a,b,c,d,e,f,g,h,i,j,k,l) a,b,c,d,e,f
#define _DCTL_TAKE_HALF_14(a,b,c,d,e,f,g,h,i,j,k,l,m,n) a,b,c,d,e,f,g
#define _DCTL_TAKE_HALF_16(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) a,b,c,d,e,f,g,h
#define _DCTL_TAKE_HALF(N, ...) _DCTL_CAT2(_DCTL_TAKE_HALF_, N)(__VA_ARGS__)
#define _DCTL_DEFINE_3(name, def, ...) enum name##_enum _DCTL_TAKE_HALF(_DCTL_NARG(__VA_ARGS__), __VA_ARGS__); static int name = (int)(def);

/* Math intrinsics (DCTL names) */
#define _powf(a, b) powf((a), (b))
#define _logf(a) logf(a)
#define _log2f(a) log2f(a)
#define _log10f(a) log10f(a)
#define _expf(a) expf(a)
#define _exp2f(a) exp2f(a)
#define _exp10f(a) powf(10.0f, (a))
#define _sqrtf(a) sqrtf(a)
#define _fabs(a) fabsf(a)
#define _fmaxf(a, b) fmaxf((a), (b))
#define _fminf(a, b) fminf((a), (b))
#define _clampf(x, lo, hi) fminf(fmaxf((x), (lo)), (hi))
#define _saturatef(x) fminf(fmaxf((x), 0.0f), 1.0f)
#define _tanhf(a) tanhf(a)
#define _cosf(a) cosf(a)
#define _sinf(a) sinf(a)
#define _atan2f(a, b) atan2f((a), (b))
#define _floorf(a) floorf(a)
#define _ceilf(a) ceilf(a)
#define _fmod(a, b) fmodf((a), (b))
#define _hypotf(a, b) hypotf((a), (b))
#define _copysignf(a, b) copysignf((a), (b))
#define _cbrtf(a) cbrtf(a)
#define _mixf(a, b, t) ((a) + ((b) - (a)) * (t))
#define _round(a) roundf(a)
#endif
