/* dctl_shim.h — minimal host-side emulation of the DaVinci Resolve DCTL
 * environment so a .dctl file can be compiled with gcc/clang as C and
 * exercised with test vectors. It is NOT a full implementation of DCTL; it
 * covers the subset used by the BNC Grade DCTLs. Never ship this file to
 * Resolve — it is only for testing. */
#ifndef DCTL_SHIM_H
#define DCTL_SHIM_H
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define __DEVICE__ static inline
#define __CONSTANT__ static const
#define __RESOLVE_VER_MAJOR__ 19
#define __RESOLVE_VER_MINOR__ 1

typedef struct { float x, y, z; } float3;
static inline float3 make_float3(float x, float y, float z) { float3 v = {x, y, z}; return v; }

/* UI parameter macros: in Resolve these create sliders/checkboxes; here we
 * declare a global initialised to the default value, which the test harness
 * may override via setters generated by DCTL_PARAM_SETTER. */
#define DCTLUI_SLIDER_FLOAT 0
#define DCTLUI_SLIDER_INT 1
#define DCTLUI_CHECK_BOX 2
#define DCTLUI_COMBO_BOX 3
#define DCTLUI_VALUE_BOX 4
#define _DCTL_PARAM_TYPE_0 float
#define _DCTL_PARAM_TYPE_1 int
#define _DCTL_PARAM_TYPE_2 int
#define _DCTL_PARAM_TYPE_4 float
#define _DCTL_CAT(a, b) a##b
#define _DCTL_TYPE(kind) _DCTL_CAT(_DCTL_PARAM_TYPE_, kind)
#define _DCTL_DISPATCH2(kind) _DCTL_DEFINE_##kind
#define _DCTL_DISPATCH(kind) _DCTL_DISPATCH2(kind)
#define DEFINE_UI_PARAMS(name, label, kind, ...) _DCTL_DISPATCH(kind)(name, __VA_ARGS__)
#define _DCTL_DEFINE_0(name, def, ...) static float name = (float)(def);
#define _DCTL_DEFINE_1(name, def, ...) static int name = (int)(def);
#define _DCTL_DEFINE_2(name, def, ...) static int name = (int)(def);
#define _DCTL_DEFINE_4(name, def, ...) static float name = (float)(def);
/* Combo boxes: DEFINE_UI_PARAMS(name, label, DCTLUI_COMBO_BOX, default, {A, B}, {"A","B"}) */
#define _DCTL_DEFINE_3(name, def, enums, labels) enum name##_enum enums; static int name = (int)(def);

/* Math intrinsics (DCTL names) */
#define _powf(a, b) powf((a), (b))
#define _logf(a) logf(a)
#define _log2f(a) log2f(a)
#define _log10f(a) log10f(a)
#define _expf(a) expf(a)
#define _exp2f(a) exp2f(a)
#define _exp10f(a) powf(10.0f, (a))
#define _sqrtf(a) sqrtf(a)
#define _fabs(a) fabsf(a)
#define _fmaxf(a, b) fmaxf((a), (b))
#define _fminf(a, b) fminf((a), (b))
#define _clampf(x, lo, hi) fminf(fmaxf((x), (lo)), (hi))
#define _saturatef(x) fminf(fmaxf((x), 0.0f), 1.0f)
#define _tanhf(a) tanhf(a)
#define _cosf(a) cosf(a)
#define _sinf(a) sinf(a)
#define _atan2f(a, b) atan2f((a), (b))
#define _floorf(a) floorf(a)
#define _ceilf(a) ceilf(a)
#define _fmod(a, b) fmodf((a), (b))
#define _hypotf(a, b) hypotf((a), (b))
#define _copysignf(a, b) copysignf((a), (b))
#define _cbrtf(a) cbrtf(a)
#define _mixf(a, b, t) ((a) + ((b) - (a)) * (t))
#define _round(a) roundf(a)
#endif
